dist: xenial
services:
  - mysql
language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: heEm2Sr8ceE+kOzdV5anl4pO8g0ibIqT44PzezDQB6jM6sHG7cqsrHM15M8X5tJV+uGpKw8/2k0uCCHgGVj3yeiD1R7cNPKXfO/HT7hknKrwQaahd3qu9diEi/hlNuJSE614iEdtY1zaFoyJViRtsprN9bJNrA0MXsjP8iQHc2kvCBKq/eelf8R56EuWK3WIkamWNIqu/OaKAFBmvvGu9FWRcA25ptpRQATjtY3K1hBZ0eiw0OWx+3XAfEvwS32ZNBLqV0HwAIffBgT/McERO4ZnAs54UcU/dxy/HxNn1wPZGeLZj1+uE8XMeDgUgAUIwxrguaMRzN2znYdigZD3QsMLFM+hvI3kk4dn3SXpktiM8lefIEcyzRBI/tlXq4RKfSyQr8Pzy46JJf9/3n6muImRI3kYggmEMMdLe3YkdiF1jtXuqpe6VQJ3PafQQUHeG2Q9woUZPWH8mngE7jd7m0WxNXuY0DX3E7LteZchLvZpho+P1mYBaHdyi0tdguGAirx7sBdz/VXY/fGKZLklmp3k7pjO+5d4Ry/o/1sSuVJH2P6FoZT5w0YPQxj1eY1dxwA1ZX+aJb2rBJbt9kYQcEBXox7xQ3dSyE9XaOGk/SvKRu0226Uy2V+UQrDMDb94pUdVd9R6QUbVvT6GsaTYwNQ2zGX/kiNi3rNynHudZQc=
branches:
  only:
  - dev
  - hotfix
  - "/^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$/"
php:
- 7.1
- 7.2
- nightly
env:
- WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="8"
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install -g lerna
- npm install
- npm run bootstrap
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- npm run test
- composer test
- lerna run test
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- npm run build:production
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XdchVIQYOB87JkkIdkIfhQUeU6jkATDaAf2MypPNoiSJKmShVyWRxXehl0b8ieZqz8WP0wciZhDXfRSufbBIxeNy+nXh7dSn0L3BMOv7Up+/lYTmBIQUtXJM6UJV1CBALgcmO4K0vFVnUQzEi1TbTQK62QUgfTJ1sQBAKB7Eg7WMhgn3sSVhV0pADRJshsOTsuVMiZ3DuDnWQ3RzGjC0deIlKCr/GO4+R6W5giR7+05WPZOB9o/+ugD2ZbeblBJIk8kt6ZcyQBbhGv1cCEoSPsyXg4B7vA15jZdabDFkMu0ebbnpxgMWCuh2PReoc7jaefyR5/c+Le5mSelFkY/wEB92VBO2TcjgEzXbf5cx7AxWaI9AFyDf7XUrqept/0xXdmpyOzgg6J6SNcOoc9rs6P24q2RGYUCTUGcynd+wTzlsWWpL1pi/ZG2A3mvHaPfCltvyGgXxTBWCI3mTClEebu+rg0GED1LDGKlwlop4wFVvX+5KzBfuo5buULIouud1deav63xBq9Td7HGcAH9N3zwEOaNjTDCc/cw9ZgzjTcOC4sbyLLeFJ6xHpONd7HtvstibSlu5aHuDd6hRD3Kgzs11JUzXMwgo3jiCWTfAZ25lDisEVmIqYS+Ea8lyCoY+BLfDcPlEeyhOtlXfRT4n2xtGPWZmgbndvtOMXDXuDds=
  file: pressbooks-book-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: pressbooks/pressbooks-book
